
# The purpose of this script is to generate predicted values based off of the 
# geom_smooth trend lines for every 1NM increment from [1, 600]NM.  
# The final data frame will have the following columns 
# DIST_NM: [1, 600]NM 
# SPECIES: BIGEYE_TUNA, YELLOWFIN_TUNA, ALL, OTHER (filter as needed)
# post_CPUE: the predicted CPUE that was generated from the post expansion data 
#             based on the geom_smooth fit 
# pre_CPUE:  the predicted CPUE that was generated from the pre expansion data 
#             based on the geom_smooth fit 
# diff_CPUE: post_CPUE - pre_CPUE


# Example Synthax 
#data_set <- "Observer Data"

generating_predicted_CPUE_data_frame.f <- function(data_set){
  
  set_panel.df <- readRDS(file.path(".",
                                  "Data",
                                  data_set,
                                  paste0("05_FullSetPanel_2000_2020.RDS"))) 
  
  # Subset for the before and after the expansion date 
  # Only capture within 600NM
  pre_expansion_FULL <- set_panel.df %>% 
    filter(SETBEGIN_DATE >= as.Date("2010-01-01") & 
             SETBEGIN_DATE < as.Date("2016-08-26"),
           DIST_NM <= 600)
  
  post_expansion_FULL <- set_panel.df %>% 
    filter(SETBEGIN_DATE >= as.Date("2016-08-26") & 
             SETBEGIN_DATE <= as.Date("2019-12-31"),
           DIST_NM <= 600)
  
  #---------
  # Loop through each species 
  # Obtain the coef for the geom_smooth function

  species <- unique(set_panel.df$ENGLISH_NAME)
  
  diff_pred_CPUE.l <- lapply(1:length(species), FUN = function(i){
    
    # Subset for one species only 
    one_species <- species[i]

    # Subset for the before and after expansion 
    pre_expansion <- pre_expansion_FULL %>% 
      filter(ENGLISH_NAME == one_species)
    
    post_expansion <- post_expansion_FULL %>% 
      filter(ENGLISH_NAME == one_species)
    
    # -------------
    # Find the predicted data that is generated by the geom_smooth
    # line when we plot CPUE against NM from PMNM boarder
    
    creating_geomsmooth_pred_values_df <- function(df, period){
      
      # Specify the geom_smooth model and run the gam regression
      model <- mgcv::gam(CPUE ~ s(DIST_NM, bs = "cs"), data = df)
      
      # Create a vecotr of NM inputs for(1, 600)
      xseq <- c(1:600)
      
      # Estimate the predicted values for the xseq range 
      pred <- predict(model, newdata = data.frame(DIST_NM = xseq), se=FALSE)
      
      # Create a data frame that has the predicted geom_smooth values for 
      # (1, 600)NM 
      model.df <- data.frame(DIST_NM = xseq, 
                             CPUE = pred,
                             SPECIES = one_species) %>% 
        doBy::renameCol("CPUE", paste0(period, "_CPUE"))
      
    }
    
    
    # Creating pre/post regression df
    pre_reg.df <- creating_geomsmooth_pred_values_df(pre_expansion, "pre")
    post_reg.df <- creating_geomsmooth_pred_values_df(post_expansion, "post")
    
    # Joining pre/post to get one data frame 
    diff_pred_CPUE_ONE_SPECIES.df <- left_join(pre_reg.df, post_reg.df, 
                                  by = c("DIST_NM", "SPECIES")) %>% 
      mutate(diff_CPUE = post_CPUE - pre_CPUE) %>% 
      dplyr::select(DIST_NM, SPECIES, post_CPUE, pre_CPUE, diff_CPUE)

    return(diff_pred_CPUE_ONE_SPECIES.df)
  })
  
  # ---------------
  # Compile final data frame for bet and yf
  diff_pred_CPUE.df <- do.call("rbind", diff_pred_CPUE.l) 
  
  return(diff_pred_CPUE.df)
}




